---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansadmin
    - name : Build image
      command: docker build -t vaishnavi062/maven-askit-1-webapp .
    - name : Push Docker Image
      command: docker push vaishnavi062/maven-askit-1-webapp
- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
   - name: 
     copy:
       src: k8s-deployment.yml
       dest: /home/ansadmin
   - name : K8S Deployment
     command: kubectl apply -f k8s-deployment.yml
